### ISSUE TITLE
No releases since the changes at the 1.0.0 tag

### ISSUE THREAD

**Issue by jimmynotjim** [hexojs/hexo-autoprefixer#21]
It's not possible to get the latest updates from this package via NPM without specifying the latest commit sha `npm install github:hexojs/hexo-autoprefixer#ccfa156` because there are no release tags published since `v1.0.0`. Would it be possible to get the latest updates published to NPM so Hexo projects can use Autoprefixer greater than `6.*.*`?

**Comment by JLHwung** [comment]
There is never a 1.0.0 release tag and the 1.0.0 package version is manually bumped at 659575fe13f0031d186040d574fc9de87dd934ee. That means there should have been a 1.0.0 release on 2015 but I don't know why it had not been published.
