### ISSUE TITLE
Use CSSNext instead of Autoprefixer

### ISSUE THREAD

**Issue by PazzaVlad** [hexojs/hexo-autoprefixer#6]
Maybe it would be more useful to use cssnext instead of autorpefixer? CSSNext already contains autorpefixer and let us use new CSS syntax. 
I can make a PR.

**Comment by JLHwung** [comment]
Sorry for the late reply, but on the late of 2018, CSSNext had long been [deprecated](https://github.com/MoOx/postcss-cssnext) in favor of `postcss-preset-env`.
